version: "3.9"
services:
  tiktok:
    build: ./src/
    ports:
      - 443:443
    volumes:
      - ./src/:/app/
    command: ["./run.sh"]
    depends_on:
      - redisdb
    environment:
      - REDISHOST=redisdb:6379
      - HTTPS=TRUE
  redisdb:
    image: redis:6-alpine
    volumes:
      - ./db:/data
  certbot:
    image: certbot/certbot
    ports:
      - 80:80