version: "3.9"
services:
  web:
    build: ./src/
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/app/
    command: ["./run.sh"]
    depends_on:
      - redisdb
    environment:
      - REDISHOST=redisdb:6379
      - SERVERPORT=8080
      - ADMINPASSWORD=secure
      - HTTPS=false
  # admin:
  #   build: ./admin/
  #   volumes:
  #     - ./admin/:/app/
  #   depends_on:
  #     - redisdb
  #   environment:
  #     - REDISHOST=redisdb:6379
  redisdb:
    image: redis:6-alpine
    volumes:
      - ./db:/data