version: "3.9"
services:
  web:
    build: ./src/
    volumes:
      - ./src/:/app/
    command: ["./run.sh"]
    depends_on:
      - redisdb
    environment:
      - REDISHOST=redisdb:6379
      - SERVERPORT=8080
      - ADMINPASSWORD=secure
      - HTTPS=false
  nginx:
    ports:
      - 80:80
      - 443:443
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot
  # admin:
  #   build: ./admin/
  #   volumes:
  #     - ./admin/:/app/
  #   depends_on:
  #     - redisdb
  #   environment:
  #     - REDISHOST=redisdb:6379
  redisdb:
    image: redis:6-alpine
    volumes:
      - ./db:/data