version: "3.9"
services:
  tiktok:
    build: ./src/
    ports:
      - 1323:1323
    volumes:
      - ./src/:/app/
    command: ["./run.sh"]
    depends_on:
      - redisdb
    environment:
      - REDISHOST=redisdb:6379
      - PORT=1323
  redisdb:
    image: redis:6-alpine
    volumes:
      - ./db:/data